import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/** Primary docs plugin (`../docs`) — order follows `sidebar_position` in frontmatter. */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
