import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/** Secondary docs plugin (`../ops`) — `09_archive` excluded in docusaurus.config.ts. */
const sidebars: SidebarsConfig = {
  opsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
